services:
  db:
    container_name: blog-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: secret
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
